### ISSUE TITLE
encountering error in running command "vcfdo --help", after a successful installation

### ISSUE THREAD

**Issue by tahirali-biomics** [IDEELResearch/vcfdo#9]
I am getting the following error which seems to be related to 'numpy'. I tried to troubleshoot this by installing different versions of 'numpy-1.25.2', 'numpy-1.26.1', I also uninstalled and reinstalled vcfdo but could not fix this issue:                                     
 [tali@cheops1 tools]$ vcfdo --help
Traceback (most recent call last):
  File "/projects/ag-demeaux/tali/tools/python3.9/Python-3.9.18/bin/vcfdo", line 14, in <module>
    np.warnings.filterwarnings("ignore")
  File "/projects/ag-demeaux/tali/tools/python3.9/Python-3.9.18/lib/python3.9/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
                                                                                                                                                                                                                                I really appreciate your help and support in resolving this problem. Thank you.

**Comment by andrewparkermorgan** [comment]
It looks like this is due to a change in `numpy` (which may trickle down into another package). When I was last actively maintaining the package I was developing against v1.19.4. I have not worked on this recently so a workaround (for now) would be to use an environment manager like `conda` to install against the above version of `numpy`.

**Comment by tahirali-biomics** [comment]
Hi Andrew, Thank you for replying to my query, I will try installing it the way you have suggested and let you know if it works.

**Comment by drobledoruiz** [comment]
I confirm this issue is raised on a conda env with python=3.8 and numpy=1.24. Tried different numpy versions but finally seems to be working with numpy=1.20.
